// Blog posts — newest first.
//
// To add a new post, copy the block below, paste it at the TOP of the array
// (right after `export const posts = [`), and fill it in:
//
//   {
//     date: '2026-07-03',            // YYYY-MM-DD
//     title: 'Your title here',
//     body: `
// Write your post here. Blank lines separate paragraphs.
// You can write as many paragraphs as you like.
//     `,
//   },
//
// That's it — save the file and the post shows up automatically.

export const posts = [
  {
    date: '2026-07-03',
    title: 'Can I Learn to Reverse Engineer Antibot in 30 Days | Day 1',
    body: `
When I was a kid, I was always fascinated by how checkout bots work. Over summer, I really had no projects
planned or anything, so I started diving deep into how a checkout bot works. Turns out it is really complicated
and I genuinely have no idea or where to start. I have a grasp or flow of how things work, but it is difficult for me
to piece it all together as each antibot is very different. 

So for my summer project, I want to learn if I could program a checkout bot, with my first primary focus being f5 shape security.
I will upload resources that I found helpful, share my progress, and hopefully be able to buy some pokemon. This is my first day,
so essentially I will be trying to build a checkout flow mainly through requests.

Another issue I ran into is that it is very difficult to get Claude or ChatGPT to teach or generate code to help. That is another
reason I think it is difficult for me to learn. Anyways, I think bot developers are so cool just by the fact they are in constant
competition. My goal is to be able to reverse engineer shape by the end of the month hopefully and get it done. Then move onto a different
antibot in the future.

Edit at 3:04AM. I really don't know how any of this works. I just got claude to de-obfuscate a challenge.js file from shopify, but that is it.
I think I will just try to create a flow however (could be insanely inefficient, but as long as it works?) and improve it from there.

Edit at 4:05AM. Ok yeah I think I am just gonna make a really crappy version of a checkout bot because this is difficult figuring out what everything
does in a folder. I will try my best to keep improving it overtime. I can't believe I have another 29 days of this.

Honestly, didn't get much done today. Solved 3 leetcodes and that was it. We will do more tomorrow.
    `,
  },
  {
  date: '2026-07-04',
    title: 'My love for CS | Day 2',
    body: `
I've officially decided that instead of just trying to use this blog for learning to solve antibot, I will just keep track of my progress.
I really love computer science, but I'm lost in a way. Using this to document my day to day life and show what I do will help me reflect whether
I am wasting my time or not.

Anyways, today I didn't do much. I am back in Jacksonville and found a very nice article that was discussing how to use PerimeterX SDK, but it required
an android emulator and Mac Silicon was not very well supported for the ones I needed to use. I return tomorrow. I completed 3 neetcode questions (currently at 8/150) where
I am doing it with a friend so we can explain code to each other and hold each other accountable.

I have also been working on a side project, where hopefully I can show more of sooner or later. I also decided I am going to work on reverse engineer nudata,
through Kohl's login. I heard this is one of the simpler ones.

2:39AM: Ok, I think I finally understand the compelete flow of how to figure out antibot. So my goal is to call requests, but requests have cookies. These cookies
are generated by javascript files that typically load initially at the opening of the page. Essentially, my goal is to find what cookies are needed (they can be in headers or a payload message is required),
locate these javascript finals (typically find the request you are interested in, look in initiators, find relevant js files and keep going down the hole), and deobfuscate these javascript files to understand
flows of the website, how cookies are generated, what the website asks for and so on.

I also learned that reading AST and using tools like Babel are significant to learn. Hopefully I am going down the right road...
    `,
  },
  {
  date: '2026-07-05',
    title: 'busy | Day 3',
    body: `
I worked on my project more today due to having assignments from my CS2 class to complete and a test soon on matrix and linear algebra. I did not reverse engineer
much, but I did "code", if you can even call it that anymore (use genAI), today by working on my side project/business. Will be continuing to work on 
this project alongside reverse engineering since genAI really does allow you to do both. I also had to drive back from Jacksonville to Orlando which took up most of
my time. 
    `,
  },
]



export function slugify(title) {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export const postsWithSlugs = posts.map((p) => ({ ...p, slug: slugify(p.title) }))

export function getPost(slug) {
  return postsWithSlugs.find((p) => p.slug === slug)
}

export function formatDate(iso) {
  return new Date(`${iso}T00:00:00`).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}
